dtb-$(CONFIG_ARCH_MSM8996) += msm8996-v2-pmi8994-cdp.dtb \
	msm8996-v2-pmi8994-mtp.dtb \
	msm8996-v2-pmi8994-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pmk8001-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v2-fluid.dtb \
	msm8996-v2-liquid.dtb \
	msm8996-v2-dtp.dtb \
	msm8996-v3-pmi8994-cdp.dtb \
	msm8996-v3-pmi8994-mtp.dtb \
	msm8996-v3-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pmk8001-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v3-pmi8996-cdp.dtb \
	msm8996-v3-pmi8996-mtp.dtb \
	msm8996-v3-pmi8996-pmk8001-cdp.dtb \
	msm8996-v3-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3-fluid.dtb \
	msm8996-v3-liquid.dtb \
	msm8996-v3-dtp.dtb \
	msm8996-v3-pm8004-mmxf-adp.dtb \
	msm8996-v3-pm8004-agave-adp.dtb \
	msm8996pro-pmi8994-cdp.dtb \
	msm8996pro-pmi8994-mtp.dtb \
	msm8996pro-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-pmi8994-pm8004-cdp.dtb \
	msm8996pro-pmi8994-pm8004-mtp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-pmi8996-cdp.dtb \
	msm8996pro-pmi8996-mtp.dtb \
	msm8996pro-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-pmi8996-pmk8001-mtp.dtb \
	apq8096pro-liquid.dtb \
	msm8996-v3.0-pmi8994-cdp.dtb \
	msm8996-v3.0-pmi8994-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-cdp.dtb \
	msm8996-v3.0-pmi8994-pm8004-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8996-cdp.dtb \
	msm8996-v3.0-pmi8996-mtp.dtb \
	msm8996-v3.0-fluid.dtb \
	msm8996-v3.0-liquid.dtb \
	msm8996-v3.0-dtp.dtb \
	apq8096-v2-pmi8994-cdp.dtb \
	apq8096-v2-pmi8994-mtp.dtb \
	apq8096-v2-pmi8994-pmk8001-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v2-liquid.dtb \
	apq8096-v2-dragonboard.dtb \
	apq8096-v2-auto-dragonboard.dtb \
	apq8096-v3-pmi8994-cdp.dtb \
	apq8096-v3-pmi8994-mtp.dtb \
	apq8096-v3-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3-pmi8996-cdp.dtb \
	apq8096-v3-pmi8996-mtp.dtb \
	apq8096-v3-liquid.dtb \
	apq8096-v3-dragonboard.dtb \
	apq8096-v3-sbc.dtb \
	apq8096-v3-auto-dragonboard.dtb \
	apq8096-v3.0-pmi8994-cdp.dtb \
	apq8096-v3.0-pmi8994-mtp.dtb \
	apq8096-v3.0-pmi8994-pm8004-cdp.dtb \
	apq8096-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8996-cdp.dtb \
	apq8096-v3.0-pmi8996-mtp.dtb \
	apq8096-v3.0-liquid.dtb \
	apq8096-v3.0-dragonboard.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8994-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-dragonboard.dtb

dtb-$(CONFIG_ARCH_MSMCOBALT) += msmcobalt-sim.dtb \
	msmcobalt-rumi.dtb \
	msmcobalt-cdp.dtb \
	msmcobalt-mtp.dtb \
	msmcobalt-v2-sim.dtb \
	msmcobalt-v2-rumi.dtb \
	msmcobalt-v2-mtp.dtb \
	msmcobalt-v2-cdp.dtb

dtb-$(CONFIG_ARCH_MDM9640) += mdm9640-sim.dtb \
	mdm9640-rumi.dtb \
	mdm9640-emmc-cdp.dtb \
	mdm9640-nand-cdp.dtb \
	mdm9640-mtp.dtb

dtb-$(CONFIG_ARCH_MDMCALIFORNIUM) += mdmcalifornium-sim.dtb \
	mdmcalifornium-rumi.dtb \
	mdmcalifornium-emmc-cdp.dtb \
	mdmcalifornium-nand-cdp.dtb \
	mdmcalifornium-emmc-mtp.dtb \
	mdmcalifornium-nand-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8937) += \
    msm8937-0.dtb \
    msm8937-10.dtb \
    msm8937-11.dtb \
    msm8937-12.dtb \
    msm8937-13.dtb \
    msm8937-14.dtb \
    msm8937-15.dtb \
    msm8937-16.dtb \
    msm8937-17.dtb \
    msm8937-18.dtb \
    msm8937-19.dtb \
    msm8937-1.dtb \
    msm8937-20.dtb \
    msm8937-21.dtb \
    msm8937-22.dtb \
    msm8937-23.dtb \
    msm8937-24.dtb \
    msm8937-25.dtb \
    msm8937-26.dtb \
    msm8937-27.dtb \
    msm8937-28.dtb \
    msm8937-29.dtb \
    msm8937-2.dtb \
    msm8937-30.dtb \
    msm8937-31.dtb \
    msm8937-32.dtb \
    msm8937-33.dtb \
    msm8937-34.dtb \
    msm8937-35.dtb \
    msm8937-36.dtb \
    msm8937-37.dtb \
    msm8937-38.dtb \
    msm8937-39.dtb \
    msm8937-3.dtb \
    msm8937-40.dtb \
    msm8937-41.dtb \
    msm8937-42.dtb \
    msm8937-43.dtb \
    msm8937-44.dtb \
    msm8937-45.dtb \
    msm8937-46.dtb \
    msm8937-47.dtb \
    msm8937-48.dtb \
    msm8937-49.dtb \
    msm8937-4.dtb \
    msm8937-50.dtb \
    msm8937-51.dtb \
    msm8937-52.dtb \
    msm8937-53.dtb \
    msm8937-54.dtb \
    msm8937-55.dtb \
    msm8937-56.dtb \
    msm8937-57.dtb \
    msm8937-58.dtb \
    msm8937-59.dtb \
    msm8937-5.dtb \
    msm8937-60.dtb \
    msm8937-61.dtb \
    msm8937-62.dtb \
    msm8937-63.dtb \
    msm8937-64.dtb \
    msm8937-65.dtb \
    msm8937-6.dtb \
    msm8937-7.dtb \
    msm8937-8.dtb \
    msm8937-9.dtb

dtb-$(CONFIG_ARCH_MSMGOLD) += msmgold-rumi.dtb \
	apqgold-pmi8937-cdp.dtb \
	apqgold-pmi8937-mtp.dtb \
	apqgold-pmi8950-cdp.dtb \
	apqgold-pmi8950-mtp.dtb \
	msmgold-pmi8937-cdp.dtb \
	msmgold-pmi8937-mtp.dtb \
	msmgold-pmi8950-cdp.dtb \
	msmgold-pmi8950-ext-codec-cdp.dtb \
	msmgold-pmi8950-mtp.dtb \
	msmgold-pmi8937-rcm.dtb \
	msmgold-pmi8950-rcm.dtb \
	msmgold-pmi8937-qrd-sku5.dtb

dtb-$(CONFIG_ARCH_MSMTITANIUM) += msmtitanium-sim.dtb \
	msmtitanium-rumi.dtb \
	msmtitanium-cdp.dtb \
	msmtitanium-mtp.dtb \
	msmtitanium-ext-codec-mtp.dtb \
	msmtitanium-qrd-sku3.dtb \
	msmtitanium-rcm.dtb \
	msmtitanium-ext-codec-rcm.dtb \
	apqtitanium-cdp.dtb \
	apqtitanium-mtp.dtb

dtb-$(CONFIG_ARCH_MDM9607) += mdm9607-rumi.dtb \
	mdm9607-cdp.dtb \
	mdm9607-mtp.dtb \
	mdm9607-rcm.dtb \
	mdm9607-mtp-sdcard.dtb

dtb-$(CONFIG_ARCH_MSM8916) += msm8952-qrd-skum.dtb \
       msm8952-cdp.dtb \
       msm8952-ext-codec-cdp.dtb \
       msm8952-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8909) += msm8909-pm8916-mtp.dtb \
	msm8909w-wtp.dtb \
	apq8009w-wtp.dtb \
	msm8909w-pm8916-mtp-ext-chg-fg.dtb


ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
